title: LEAP Lab Logistics
remote_theme: just-the-docs/just-the-docs

# Enable sidebar
just_the_docs:
  show_sidebar: true
  collections:
    eehpc-cluster:
      name: "EEHPC Cluster"
      nav_fold: true
    travel-grants:
      name: "Travel Grants"
      nav_fold: true

# Navigation bar (sidebar)
nav:
  - title: Home
    url: /

  - title: EEHPC Cluster
    section: eehpc-cluster

  - title: Travel Grants
    section: travel-grants
